project_id = "owvwwslbwbarvmjjtlkz"

[functions.create-live-room]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.notify-followers]
verify_jwt = false

[functions.check-starting-soon]
verify_jwt = false

[functions.notify-reschedule]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-dm-push]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.purchase-ticket]
verify_jwt = false
